name: Sample use

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

jobs:
  use:
    name: Use in ${{ matrix.dir }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dir:
          - "sample-cjs-use"
          - "sample-esm-use"
          - "sample-ts-use"

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@a1800f471a0bc25cddac36bb13e6f436ddf341d7 # v1
        with:
          bun-version: 1.0.6
      - run: bun install
      - run: bun run build

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm
      - name: Install
        working-directory: ${{ matrix.dir }}
        run: npm install
      - name: Run
        working-directory: ${{ matrix.dir }}
        run: npm run test
